### ISSUE TITLE
Unable to define Pid file location

### ISSUE THREAD

**Issue by felipeclopes** [tweetstream/tweetstream#145]
I'm trying to monit my tweetstream with monit, though I could not find a way to set the location of the pid and the log in separated folder.

Do you know how to do this?

**Comment by sweetdub** [comment]
I had the same issue, and I figured it out using the param `dir` for daemonize.

Here's my stream client daemon code:

    @client = TweetStream::Daemon.new('streamer', log_output: true, log_dir: File.join(root, 'log'), multiple: true, dir: File.join(root, 'tmp'))

You may use the `app_name` param too.

Solution found here:
https://github.com/thuehlinger/daemons/issues/20
