### ISSUE TITLE
Setting up Daemon -> ActiveRecord in Rails app

### ISSUE THREAD

**Issue by zachwhelchel** [tweetstream/tweetstream#183]
Struggling to find a basic setup guide for added Tweetstream to my Rails app. Here's what I have... but its not triggering and creating objects. I also had to strip the logging code out as it kept erroring out, saying it didn't have permission to write to a log file :/

/config/initializers/tweetstream.rb
```ruby
TweetStream.configure do |config|
  config.consumer_key       = ENV['TWITTER_CONSUMER_KEY']
  config.consumer_secret    = ENV['TWITTER_CONSUMER_SECRET']
  config.oauth_token        = ENV['TWITTER_OAUTH_TOKEN']
  config.oauth_token_secret = ENV['TWITTER_OAUTH_TOKEN_SECRET']
  config.auth_method        = :oauth
end
```

/bin/tweets_searcher.rb
```ruby
require 'rubygems'
require 'tweetstream'

ENV["RAILS_ENV"] ||= "development"

root = File.expand_path(File.join(File.dirname(__FILE__), '..'))
require File.join(root, "config", "environment")

daemon = TweetStream::Daemon.new('tracker')
daemon.on_inited do
  ActiveRecord::Base.connection.reconnect!
end
daemon.track('appidea') do |tweet|
  AppIdea.create_from_tweet
end
```

/app/models/app_idea.rb
```ruby
class AppIdea < ActiveRecord::Base

  def create_from_tweet
    logger.debug "Should be creating an AppIdea."
    AppIdea.create!(
      tweet: 'example'
    )
  end

end
```

I then run this line to run the script: 
bundle exec ruby bin/tweets_searcher.rb start

But when I tweet something that includes "#appidea" it doesn't create a new object. Any thoughts? It seems like a lot of people are looking for a simple tutorial on how to get something very similar to this working. I've been trying to piece together different parts from different posts but no luck.

**Comment by stve** [comment]
Please see the full example here: https://github.com/tweetstream/tweetstream-rails-example
