### ISSUE TITLE
Ignoring retweets

### ISSUE THREAD

**Issue by hakkiplaten** [tweetstream/tweetstream#191]
How'd one go about ignoring reteweets from say the example in the docs?

```
TweetStream::Client.new.follow(14252, 53235) do |status|
  puts "#{status.text}"
end
```

**Comment by stve** [comment]
@hakkiplaten the easiest way is to add conditions to your message handling code:

```ruby
TweetStream::Client.new.follow(14252, 53235) do |status|
  if meets_your_requirements?(status)
    # do something with the status
  end
end
```

If you can be more specific about what you are trying to do I can probably suggest some additional approaches.

**Comment by hakkiplaten** [comment]
@stve I've decided to go with:
```
TweetStream::Client.new.follow(14252, 53235) do |status|
  unless status.starts_with? "RT"
    ...
  end
end
```

Do let me know if there are better ways.

Thanks.
