### ISSUE TITLE
Support for multiple user streams, with configuration using auth token and auth token secret

### ISSUE THREAD

**Issue by ProjectDent** [tweetstream/tweetstream#192]
As the Twitter site streams API is no longer available, I'm wanting my server to access a number of different user streams. As the configuration seems to happen on a class level and not at an instance level, I'm unsure how I'd allow a separate instance logging in for each user. I'm not using their username and password, but their auth token and auth token secret.

Perhaps I've missed something and this is already possible?

**Comment by stve** [comment]
Clients can be instantiated with credentials which should allow you to run multiple clients. That should meet your use case:

```ruby
credentials = {
  consumer_key: 'abcdefghijklmnopqrstuvwxyz'
  consumer_secret: '0123456789',
  oauth_token: 'abcdefghijklmnopqrstuvwxyz',
  oauth_token_secret: '0123456789',
}

client = TweetStream::Client.new(credentials)
client.userstream do |status|
  # do something with the status
end
```
